run:
	python3 Colleen.py > tmp_Colleen
	python3 Grace.py
	python3 Sully.py
	diff Colleen.py tmp_Colleen
	diff Grace.py Grace_kid.py

clean:
	rm -f tmp_Colleen
	rm -f Grace_kid.py
	rm -f Sully_0.py
	rm -f Sully_1.py
	rm -f Sully_2.py
	rm -f Sully_3.py
	rm -f Sully_4.py
	rm -f Sully_5.py
